Update patch set 1
Patch Set 1:

need to add an #if to check that we have poll64 before i fortify a non-existent function :-)

  In file included from packages/apps/TV/jni/DvbManager.cpp:24:
  In file included from out/soong/ndk/sysroot/usr/include/sys/poll.h:1:
  In file included from out/soong/ndk/sysroot/usr/include/poll.h:54:
  out/soong/ndk/sysroot/usr/include/bits/fortify/poll.h:85:37: error: cannot take address of function 'ppoll64' because parameter 1 has pass_object_size attribute
  return __call_bypassing_fortify(ppoll64)(fds, fd_count, timeout, mask);
  ^

Patch-set: 1
Reviewer: Elliott Hughes <1003224@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0