Update patch set 4
Patch Set 4: Presubmit-Ready+1

No pony for us because latin input method had a problem.

java.lang.AssertionError: Error details:
system_app_crash: Process: com.google.android.inputmethod.latin
PID: 3423
Flags: 0x38cab    ...
expected:<0> but was:<1>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at com.android.devicehealthchecks.CrashCheckBase.checkCrash(CrashCheckBase.java:78)
at com.android.devicehealthchecks.CrashCheck.system_app_crash(CrashCheck.java:50)

Sigh...

Patch-set: 4
Reviewer: Erik Kline <1000451@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=+1