Update patch set 1
Patch Set 1:

> I tried to build x86 emulator with clang and, after your patch is
 > applied, I got the following error:
 > 
 > target  C: libc_gdtoa <= bionic/libc/upstream-openbsd/lib/libc/gdtoa/hdtoa.c
 > bionic/libc/upstream-openbsd/lib/libc/gdtoa/hdtoa.c:228:11: error:
 > incomplete definition of type 'struct ieee_ext'
 > *sign = p->ext_sign;
 > ~^
 > 
 > it seems some upstream-* files have other issues as well (some may
 > be caused by particular gcc feature not supported by clang)

yeah, sorry, i commented about that on another change. that's a bug with our platform prebuilt clang (it's built for ld80 rather than ld128). srhines: do you have an idea of the ETA for that fix? should i raise an internal bug or is there no danger of us forgetting this?

 > As for x86/x86_64 assemblies subset your patch is fixing suffixes
 > correctly in these particular cases and you are right there are
 > more…
 > 
 > Generally, we don't have any preferences about the compiler choice
 > for building bionic at this point. It would be interesting though
 > to see the implications of the potential compiler change (do you
 > have any insights?).

we don't have a preference either. this all came about because i had a GCC error building the dns code that didn't make any sense; i wanted to build with clang to get a usable diagnostic. i hope to get an internal continuous build with clang at some point so we don't bit rot, but -- other than better diagnostics -- i don't have any particular preference for clang.

 > In any case we can fix suffixes in the rest of the x86[_64]
 > functions in the near future.

since i don't think this change is useful (because it's only a partial fix for one x86/x86-64 variant), i'll abandon it and wait for you guys to upload a full fix then. (there's no hurry unless you guys have a strong preference to have libc built with clang for x86/x86-64.)

Patch-set: 1
Reviewer: Elliott Hughes <1003224@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0