Update patch set 1
Patch Set 1:

I found that the MIPS build breaks with this patch:

prebuilts/gcc/linux-x86/mips/mipsel-linux-android-4.6/bin/mipsel-linux-android-gcc -I bionic/libc/stdlib -I bionic/libc/string -I bionic/libc/stdio -I external/safe-iop/include -I bionic/libc -I out/target/product/generic_mips/obj/STATIC_LIBRARIES/libc_common_intermediates -I libnativehelper/include/nativehelper @out/target/product/generic_mips/obj/STATIC_LIBRARIES/libc_common_intermediates/import_includes -isystem system/core/include -isystem hardware/libhardware/include -isystem hardware/libhardware_legacy/include -isystem hardware/ril/include -isystem libnativehelper/include -isystem frameworks/native/include -isystem frameworks/native/opengl/include -isystem frameworks/av/include -isystem frameworks/base/include -isystem frameworks/base/opengl/include -isystem external/skia/include -isystem out/target/product/generic_mips/obj/include -isystem bionic/libc/arch-mips/include -isystem bionic/libc/include -isystem bionic/libstdc++/include -isystem bionic/libc/kernel/common -isystem bionic/libc/kernel/arch-mips -isystem bionic/libm/include -isystem bionic/libm/include/mips -isystem bionic/libthread_db/include -c  -fno-exceptions -Wno-multichar -O2 -fomit-frame-pointer -fno-strict-aliasing -funswitch-loops -Ulinux -U__unix -U__unix__ -Umips -fpic -ffunction-sections -fdata-sections -funwind-tables -Werror=format-security -EL -march=mips32r2 -mtune=mips32r2 -mips32r2 -mhard-float -include system/core/include/arch/linux-mips/AndroidConfig.h -I system/core/include/arch/linux-mips/ -Wno-unused-but-set-variable -fno-strict-volatile-bitfields -Wno-psabi -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -DNDEBUG -g -Wstrict-aliasing=2 -fgcse-after-reload -frerun-cse-after-loop -frename-registers -DNDEBUG -UDEBUG   -DWITH_ERRLIST -DANDROID_CHANGES -DUSE_LOCKS -DREALLOC_ZERO_BYTES_FREES -D_LIBC=1 -DFLOATING_POINT -DINET6 -Ibionic/libc/private -DUSE_DL_PREFIX -DPOSIX_MISTAKE -DLOG_ON_HEAP_ERROR -std=gnu99 -include upstream-netbsd/netbsd-compat.h -DTM_GMTOFF=tm_gmtoff -DUSG_COMPAT=1 -fstrict-aliasing -DANDROID_SMP=0    -D__ASSEMBLY__  -MD -MF out/target/product/generic_mips/obj/STATIC_LIBRARIES/libc_common_intermediates/arch-mips/syscalls/__sys_clone.d -o out/target/product/generic_mips/obj/STATIC_LIBRARIES/libc_common_intermediates/arch-mips/syscalls/__sys_clone.o bionic/libc/arch-mips/syscalls/__sys_clone.S
bionic/libc/include/assert.h: Assembler messages:
bionic/libc/include/assert.h:63: Error: unrecognized opcode `void __assert(const char*,int,const char*)'
bionic/libc/include/assert.h:64: Error: unrecognized opcode `void __assert2(const char*,int,const char*,const char*)'

Patch-set: 1