Update patch set 1
Patch Set 1:

https://reviews.llvm.org/D41512 has discussions about this noisy warning.
Many other Android projects were hit because they use -W or -Wextra.
I found two places under bionic when building for full-eng target:

 bionic/libc/bionic/arpa_inet.cpp:52:18: error: result of comparison 'unsigned long' > 4294967295 is always false [-Werror,-Wtautological-type-limit-compare]
 bionic/libc/private/../../../external/dlmalloc/malloc.c:4314:40: error: result of comparison 'size_t' (aka 'unsigned int') > 4294967295 is always false [-Werror,-Wtautological-type-limit-compare]

Patch-set: 1
Reviewer: Chih-hung Hsieh <1052399@85c56323-6fa9-3386-8a01-6480fb634889>