Update patch set 1
Patch Set 1: Fails

This doesn't seem to compile for me - am I missing a dependency?


--------------------
bionic/libc/unistd/brk.c:34: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'char'
bionic/libc/unistd/brk.c: In function 'brk':
bionic/libc/unistd/brk.c:43: error: '__bionic_brk' undeclared (first use in this function)
bionic/libc/unistd/brk.c:43: error: (Each undeclared identifier is reported only once
bionic/libc/unistd/brk.c:43: error: for each function it appears in.)
make: *** [out/target/product/generic/obj/STATIC_LIBRARIES/libc_common_intermediates/unistd/brk.o] Error 1

--------------------

Patch-set: 1