Update patch set 14
Patch Set 14:

> The error is:
 > bionic/tests/grp_pwd_test.cpp:214:26: error: use of undeclared
 > identifier 'android_id_count'
 > for (size_t n = 0; n < android_id_count; ++n) {
 > ^
 > bionic/tests/grp_pwd_test.cpp:215:23: error: use of undeclared
 > identifier 'android_ids'
 > ASSERT_TRUE(exist[android_ids[n].aid]);
 > ^
 > bionic/tests/grp_pwd_test.cpp:444:26: error: use of undeclared
 > identifier 'android_id_count'
 > for (size_t n = 0; n < android_id_count; ++n) {
 > ^
 > bionic/tests/grp_pwd_test.cpp:445:23: error: use of undeclared
 > identifier 'android_ids'
 > ASSERT_TRUE(exist[android_ids[n].aid]);
 > ^
 > You can reproduce locally with make checkbuild

So the higher level question is how do we want to fix this.
We could leave the test and have it include the generated header as well, is that what you would want?

Patch-set: 14
Reviewer: William C Roberts <1013433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0