Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> you have to click through to sponge, then click on "logs" on the left,
> then download the host log, then search for " FAILED ". (i've been
> complaining about this for years, but -- despite the fact that my
> native test failures showed up directly in sponge when i was in
> google3 ten years ago -- they claim they can't do this without
> rewriting everything.)

Good to know. I didn't realize the gtest failure output was available.

For this failure:

> dlerror: dlopen failed: library "libdlext_test_recursive.so" not found

There's a list of libraries in bionic itself (bionic/tests/Android.bp) that needs updating. Something like:

cc_test {
    name: "bionic-unit-tests",
    ...
    required: [
        ...
        "libdlext_test_recursive",
        ...
    ],
}

I think apct doesn't run the cts wrapper program:
http://cs/apct/bionic/native_test.gcl

We'll also need to update the cts test list in cts/tests/tests/bionic/Android.build.copy.libs.mk.

That can be tested with "atest CtsBionicTestCases" in aosp/master. If you run that in goog/master, you might hit b/123589917. (That issue has had some CLs go in; maybe it's fixed?)

There's a similar list of libraries in pts (in goog/master and goog/pi-dev-plus-aosp) for its suspend_resume testing. Maybe we'd update just the list in goog/master, or maybe we'd just let the test fail. The suspend_resume test doesn't actually care whether the Bionic tests pass or fail -- it's just trying to verify that a suspend/resume cycle doesn't make the device faster or slower. The PtsBionicDeviceTestCases target must keep building, though.

The pts list is especially bad, but the cts and bionic lists aren't great either.

Patch-set: 2
Reviewer: Gerrit User 1229339 <1229339@85c56323-6fa9-3386-8a01-6480fb634889>