Update patch set 1
Patch Set 1:

this breaks chromium_org for x86-64 (maybe others too, but x86-64 is what i built).

external/chromium_org/sandbox/linux/seccomp-bpf/trap.cc: In function 'bool {anonymous}::GetIsInSigHandler(const ucontext_t*)':
external/chromium_org/sandbox/linux/seccomp-bpf/trap.cc:48:60: error: invalid const_cast from type 'const ucontext::<anonymous union>*' to type 'sigset_t* {aka long unsigned int*}'
   return sigismember(const_cast<sigset_t*>(&ctx->uc_sigmask), SIGBUS);
                                                            ^
external/chromium_org/sandbox/linux/seccomp-bpf/trap.cc:49:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^

(note that the comment is wrong. sigismember does take const sigset_t*.)

it looks like the problem is that our LP32 uc_sigmask isn't sigset_t --- it's an anonymous union of sigset_t and uint32_t[2] to try to paper over the fact that the LP32 bionic sigset_t was smaller than the kernel sigset_t. we could fix that by changing this to a reinterpret_cast<const sigset_t*> and removing all the custom .h files with the duplicate definitions (that the #define in this change avoids #including), but i guess i should probably change bionic's uc_sigmask so it's a sigset_t and then just have some anonymous padding instead...

Patch-set: 1