Update patch set 3
Patch Set 3:

wtf... someone's rewriting my header...

out/soong/ndk/sysroot/usr/include/android/legacy_signal_inlines.h looks like this:

  #if __ANDROID_API__ < __ANDROID_API_L__

  /* These weren't introduced until L. */

  #if __ANDROID_API__ >= 21
  int __libc_current_sigrtmax() __attribute__((__weak__));
  int __libc_current_sigrtmin() __attribute__((__weak__));
  #endif /* __ANDROID_API__ >= 21 */

and that extra #if breaks the whole thing, leaving me with:

  out/soong/ndk/sysroot/usr/include/android/legacy_signal_inlines.h:53:7: error: use of undeclared identifier '__libc_current_sigrtmax'
    if (__libc_current_sigrtmax) return __libc_current_sigrtmax();

Patch-set: 3
Reviewer: Elliott Hughes <1003224@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0