Update patch set 1
Patch Set 1:

This caused a problem with building libstdc++ from gcc 5.0:

/aivchenk/android_toolchain_gnu/gcc_obj/x86_64-linux-android/libstdc++-v3/include/x86_64-linux-android/bits/ctype_base.h:44:35: error: ‘_U’ was not declared in this scope
     static const mask upper     = _U;

should I front-port this patch (a1d2625be0186dc4970774bced8787f3f5f234bf) to gcc?

Patch-set: 1
Reviewer: Alexander Ivchenko <1017368@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0