Update patch set 1
Patch Set 1:

I don't like publicly declaring the fortify_source functions. This implies that they're part of an official API, as opposed to just an implementation artifact. Nobody should ever be using these APIs normally.

This also introduces inconsistencies between glibc and bionic. glibc doesn't publicly declare these functions. If you try to use them, you end up getting a compiler warning, even though the code links. IMHO, we should strive for the same thing in bionic.

===== BEGIN =====
#include <fcntl.h>
#include <unistd.h>

int main() {
  int fd = __open_2("/dev/null", O_RDONLY);
  close(fd);
  return 0;
}
===== END =====

nnk@nnk:~$ gcc -Wall foo.c -o foo
foo.c: In function ‘main’:
foo.c:6:3: warning: implicit declaration of function ‘__open_2’ [-Wimplicit-function-declaration]

Patch-set: 1