Update patch set 2
Patch Set 2:

here's a worse example...

the original bug is https://code.google.com/p/android/issues/detail?id=64374 which is basically "please use struct in_addr rather than __be32 in ip_mreq_source and ip_msfilter".

if we try to #define/#include/#undef to move the uapi structs out of the way, we run into trouble if someone #includes the <linux/in.h> header directly.

if we try to rename the uapi struct when we run the uapi headers through the lawyer-approved python script, we can't build iproute2:

  In file included from external/iproute2/lib/ll_proto.c:20:
  bionic/libc/include/netinet/in.h:48:8: error: redefinition of 'ip_mreq_source'
  struct ip_mreq_source {
         ^
  external/iproute2/lib/../include/linux/in.h:177:8: note: previous definition is here
  struct ip_mreq_source {
         ^
  In file included from external/iproute2/lib/ll_proto.c:20:
  bionic/libc/include/netinet/in.h:54:8: error: redefinition of 'ip_msfilter'
  struct ip_msfilter {
         ^
  external/iproute2/lib/../include/linux/in.h:183:8: note: previous definition is here
  struct ip_msfilter {
         ^

"how does this work on glibc?" you ask...

via the horrors of <linux/libc-compat.h>, which, well, i'll let it speak for itself:

 * Define compatibility macros that are used to control the inclusion or
 * exclusion of UAPI structures and definitions in coordination with another
 * userspace C library.
 *
 * This header is intended to solve the problem of UAPI definitions that
 * conflict with userspace definitions. If a UAPI header has such conflicting
 * definitions then the solution is as follows:
 *
 * * Synchronize the UAPI header and the libc headers so either one can be
 *   used and such that the ABI is preserved. If this is not possible then
 *   no simple compatibility interface exists (you need to write translating
 *   wrappers and rename things) and you can't use this interface.
 *
 * Then follow this process:
 *
 * (a) Include libc-compat.h in the UAPI header.
 *      e.g. #include <linux/libc-compat.h>
 *     This include must be as early as possible.
 *
 * (b) In libc-compat.h add enough code to detect that the comflicting
 *     userspace libc header has been included first.
 *
 * (c) If the userspace libc header has been included first define a set of
 *     guard macros of the form __UAPI_DEF_FOO and set their values to 1, else
 *     set their values to 0.
 *
 * (d) Back in the UAPI header with the conflicting definitions, guard the
 *     definitions with:
 *     #if __UAPI_DEF_FOO
 *       ...
 *     #endif
 *
 * This fixes the situation where the linux headers are included *after* the
 * libc headers. To fix the problem with the inclusion in the other order the
 * userspace libc headers must be fixed like this:
 *
 * * For all definitions that conflict with kernel definitions wrap those
 *   defines in the following:
 *   #if !__UAPI_DEF_FOO
 *     ...
 *   #endif
 *
 * This prevents the redefinition of a construct already defined by the kernel.

the granularity is often weird too. in this case, __UAPI_DEF_IP_MREQ actually guards:

1. ip_mreq
2. ip_mreqn
3. ip_mreq_source
4. ip_msfilter
5. IP_MSFILTER_SIZE
6. group_req
7. group_source_req
8. group_filter
9. GROUP_FILTER_SIZE

despite the fact that there's nothing wrong with the uapi group*/GROUP* stuff.

so my choices are:

1. hack our copy of iproute2 to remove its include/linux/in.h.

2. copy *all* of the above from the uapi header and get a change upstreamed to the kernel that adds bionic cruft to libc-compat.h alongside the existing glibc cruft, and add the "#if !__UAPI_DEF_IP_MREQ" to bionic.

3. just add "#if !__UAPI_DEF_IP_MREQ" to bionic and get away with it in the short term and worry about doing something better another day, since iproute2 is probably the only thing on the planet that tries to mix its own copy of upstream uapi headers with libc headers...

Patch-set: 2
Reviewer: Elliott Hughes <1003224@85c56323-6fa9-3386-8a01-6480fb634889>