Update patch set 7
Patch Set 7:

> PASS: All checks passed.
 > 
 > PASS: Built aosp-master-ndk/linux. See https://android-build.googleplex.com/builds/pending/P3038677/linux/latest
 > 
 > This is pure great!
 > 
 > Found a submit queue bug? Have a question? http://go/treehugger-submitqueue-bug

Weird my local build for aosp_x86_64-eng:

FAILED: PWD=/proc/self/cwd prebuilts/clang/host/linux-x86/clang-2812033/bin/clang++ -c -Ibionic/libc/stdio -Iexternal/jemalloc/include -Ibionic/libstdc++/include -isystem system/core/include -isystem system/media/audio/include -isystem hardware/libhardware/include -isystem hardware/libhardware_legacy/include -isystem hardware/ril/include -isystem libnativehelper/include -isystem frameworks/native/include -isystem frameworks/native/opengl/include -isystem frameworks/av/include -isystem frameworks/base/include -isystem bionic/libc/arch-x86_64/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/common -isystem bionic/libc/kernel/uapi/asm-x86 -Ilibnativehelper/include/nativehelper -Ibionic/libc -Iout/soong/.intermediates/bionic/libc/libc_bionic_ndk/android_x86_64_static -Iout/soong/.intermediates/bionic/libc/libc_bionic_ndk/android_x86_64_static/gen  -fno-exceptions -Wno-multichar -O2 -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -ffunction-sections -fno-short-enums -fstrict-aliasing -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Werror=pointer-to-int-cast -Werror=int-to-pointer-cast -Werror=implicit-function-declaration -O2 -g -fno-strict-aliasing -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -DNDEBUG -UDEBUG -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -nostdlibinc -m64 -march=x86-64 -DUSE_SSSE3 -mssse3 -msse4 -msse4.1 -msse4.2 -mpopcnt -D_LIBC=1 -Wall -Wextra -Wunused -Wno-deprecated-declarations -Werror=pointer-to-int-cast -Werror=int-to-pointer-cast -Werror=type-limits -Werror -Wframe-larger-than=2048 -target x86_64-linux-android -Bprebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9/x86_64-linux-android/bin -DANDROID_STRICT -fPIC  -Iout/soong/.intermediates/bionic/libc/generated_android_ids/gen -Wold-style-cast -Wsign-promo -Wno-inconsistent-missing-override -fno-rtti  -std=gnu++14 -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=null-dereference -Werror=return-type -MD -MF out/soong/.intermediates/bionic/libc/libc_bionic_ndk/android_x86_64_static/obj/bionic/libc/bionic/grp_pwd.o.d -o out/soong/.intermediates/bionic/libc/libc_bionic_ndk/android_x86_64_static/obj/bionic/libc/bionic/grp_pwd.o bionic/libc/bionic/grp_pwd.cpp
bionic/libc/bionic/grp_pwd.cpp:47:10: fatal error: 'generated_android_ids.h' file not found
#include "generated_android_ids.h"
         ^
1 error generated.

Patch-set: 7